### Imports

In [6]:
import tensorflow as tf
from tensorflow import linalg as lina # linear algebra
import numpy as np
import pandas as pd

print("Using TensorFlow version:", tf.__version__)

Using TensorFlow version: 2.10.0-dev20220405


# Tensors

## Creation

In [7]:
arr = np.reshape(np.arange(12), (3, 4))
x = tf.constant(arr)
y = tf.constant(list(np.transpose(arr)))
x,y

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])>)

In [8]:
tf.ones((2,2), tf.int8), tf.zeros((3,4))

(<tf.Tensor: shape=(2, 2), dtype=int8, numpy=
 array([[1, 1],
        [1, 1]], dtype=int8)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)>)

## Attributes

In [9]:
x.ndim, x.shape, x.dtype, x.numpy(), x.shape.as_list()

(2,
 TensorShape([3, 4]),
 tf.int32,
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 [3, 4])

## Indexing & Slicing

In [10]:
x[0][2].numpy(), x[0,2].numpy(), x[1:], x[:-2]

(2,
 2,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])>,
 <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[0, 1, 2, 3]])>)

## Reshaping

In [11]:
tf.reshape(x, (2,6))

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])>

## Arithmetics

In [12]:
x * 5, x % 2

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  5, 10, 15],
        [20, 25, 30, 35],
        [40, 45, 50, 55]])>,
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[0, 1, 0, 1],
        [0, 1, 0, 1],
        [0, 1, 0, 1]])>)

Matrix multiplication

In [13]:
tf.constant([1,2,3,4], shape=(1,4)) @ tf.transpose(x)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 20,  60, 100]])>

Dot Product

In [14]:
tf.tensordot(tf.constant([1,2,3]),tf.constant([1,2,3]), 1)

<tf.Tensor: shape=(), dtype=int32, numpy=14>

## Matrix Operations

### Transpose

In [15]:
t = tf.constant(tf.reshape(np.arange(27), (3,3,3)))
t, tf.transpose(t, [0,2,1]), tf.transpose(t)

(<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
 array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])>,
 <tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
 array([[[ 0,  3,  6],
         [ 1,  4,  7],
         [ 2,  5,  8]],
 
        [[ 9, 12, 15],
         [10, 13, 16],
         [11, 14, 17]],
 
        [[18, 21, 24],
         [19, 22, 25],
         [20, 23, 26]]])>,
 <tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
 array([[[ 0,  9, 18],
         [ 3, 12, 21],
         [ 6, 15, 24]],
 
        [[ 1, 10, 19],
         [ 4, 13, 22],
         [ 7, 16, 25]],
 
        [[ 2, 11, 20],
         [ 5, 14, 23],
         [ 8, 17, 26]]])>)

### Determinant

In [16]:
b = tf.constant([[1,2],[2,1]], dtype=tf.float32)
lina.det(b), np.linalg.det(b)

(<tf.Tensor: shape=(), dtype=float32, numpy=-3.0>, -3.0)

### Inverse

In [17]:
lina.inv(b), lina.inv(b) @ b

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.33333334,  0.6666667 ],
        [ 0.6666667 , -0.33333334]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 0.],
        [0., 1.]], dtype=float32)>)

## Norms

In [18]:
x, lina.norm(tf.cast(x, float), 2)

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])>,
 <tf.Tensor: shape=(), dtype=float32, numpy=22.494444>)

In [19]:
lina.norm(tf.constant([4.,0,0]),2)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>